### ISSUE TITLE
Is there any similar library for iOS?

### ISSUE THREAD

**Issue by asmaan** [nascentdigital/nascent-toolkit-android#1]
Guys

Is there any similar library for iOS?

**Comment by ahinton-Nascent** [comment]
There is but I wouldn’t recommend using it, it’s a little out of date now.

If you’re looking for a library to help with network service calls, one of our teammebers used https://github.com/AFNetworking/AFNetworking on her last project and highly recommends it.

On Mar 27, 2015, at 8:15 AM, asmaan <notifications@github.com<mailto:notifications@github.com>> wrote:

Guys

Is there any similar library for iOS?

**Comment by asmaan** [comment]
I am not asking for services library.I am asking for Observers based library which can observe value for keys.

**Comment by ahinton-Nascent** [comment]
That’s already natively built into Objective-C, no need for an external library

Look up KVO (Key Value Observers)

On Mar 27, 2015, at 10:21 AM, asmaan <notifications@github.com<mailto:notifications@github.com>> wrote:

I am not asking for services library.I am asking for Observers based library which can observe value for keys.

**Comment by Polynezeas** [comment]
@ronathan, why did you close this? We need a toolkit!!!!

**Comment by ronathan** [comment]
Sorry, issue was closed by accident while playing around with Ship 2.0.

**Comment by Polynezeas** [comment]
@ronathan don't let it happen again, I'll let you off this time because you're handsome.

**Comment by ronathan** [comment]
It took me a long time to realize who you were haha. In which case, I'm going to close this issue.
